In [1]:
import numpy as np
import matplotlib.pyplot as plt
import csv
import pandas as pd
from csv import reader
import seaborn as sns

In [2]:
df = pd.read_csv('box2hrz-007с.csv')
df

,# id,snap_id,uid,x,y,z,x_pixel,y_pixel,i_sector,M500_msolh,...,gas_frac,star_frac,T_kev,Lx_ergs,Y500c,M_sat_M_cD,cshift,vx,vy,vz
0,860542,28,0,208791.220,203940.950,349847.000,9718,6891,6,1.011170e+15,...,0.125776,0.028659,9.122520,37.872100,102.308640,0.027390,0.027437,-259.72600,-82.91320,-202.92100
1,860543,28,1,314122.000,24372.678,278202.310,14620,15249,15,5.412350e+14,...,0.112946,0.030866,5.959630,7.914490,48.730761,0.111877,0.011779,-282.64600,1.06033,-293.46200
2,860544,28,2,83855.367,206624.140,144593.690,3903,6766,4,7.260400e+14,...,0.120374,0.022724,6.144960,11.553600,59.058935,0.085323,0.063623,-40.43990,-160.57900,-72.43460
3,860545,28,3,327261.750,233165.060,209430.580,15232,5531,7,6.286450e+14,...,0.116089,0.027928,6.192280,34.833100,54.705239,0.063246,0.037204,-9.51925,251.43900,-118.92500
4,860546,28,4,183444.060,193161.880,332979.030,8538,7393,6,2.217660e+14,...,0.116187,0.026047,3.689910,2.097220,23.053572,0.216284,0.028688,870.24200,617.94800,-509.89900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10424,870966,28,15074,304444.090,76153.484,125475.130,14170,12839,15,7.152720e+12,...,0.044805,0.034122,0.390212,0.003211,0.299250,0.317329,0.082210,333.19500,172.07700,70.60560
10425,870967,28,15240,165232.340,66270.766,57933.605,7690,13299,13,7.388280e+12,...,0.054074,0.034059,0.387234,0.007786,0.362322,0.453900,0.090051,-99.56510,104.02400,142.64100
10426,870968,28,15272,272347.840,305951.750,303981.470,12676,2143,3,7.231790e+12,...,0.033251,0.032024,0.447326,0.001472,0.255544,0.001987,0.043893,-333.16800,-55.94300,261.41000
10427,870969,28,15289,111759.160,122749.100,339429.380,5201,10670,9,7.085930e+12,...,0.055285,0.030725,0.341775,0.007282,0.322402,0.242687,0.121855,75.08240,19.83800,-7.41744
10428,870970,28,15438,276200.190,56579.359,53757.617,12855,13750,15,7.295310e+12,...,0.058925,0.032900,0.402439,0.007969,0.408591,0.606316,0.039734,-440.71800,322.18000,-177.03000

In [3]:
df['fossil'] = 'no'
df.loc[(df.M_sat_M_cD<=0.22)&(df.Lx_ergs>=0.1),'fossil']='yes'
## здесь используется критерий из диссертации Ragagnin
df

,# id,snap_id,uid,x,y,z,x_pixel,y_pixel,i_sector,M500_msolh,...,star_frac,T_kev,Lx_ergs,Y500c,M_sat_M_cD,cshift,vx,vy,vz,fossil
0,860542,28,0,208791.220,203940.950,349847.000,9718,6891,6,1.011170e+15,...,0.028659,9.122520,37.872100,102.308640,0.027390,0.027437,-259.72600,-82.91320,-202.92100,yes
1,860543,28,1,314122.000,24372.678,278202.310,14620,15249,15,5.412350e+14,...,0.030866,5.959630,7.914490,48.730761,0.111877,0.011779,-282.64600,1.06033,-293.46200,yes
2,860544,28,2,83855.367,206624.140,144593.690,3903,6766,4,7.260400e+14,...,0.022724,6.144960,11.553600,59.058935,0.085323,0.063623,-40.43990,-160.57900,-72.43460,yes
3,860545,28,3,327261.750,233165.060,209430.580,15232,5531,7,6.286450e+14,...,0.027928,6.192280,34.833100,54.705239,0.063246,0.037204,-9.51925,251.43900,-118.92500,yes
4,860546,28,4,183444.060,193161.880,332979.030,8538,7393,6,2.217660e+14,...,0.026047,3.689910,2.097220,23.053572,0.216284,0.028688,870.24200,617.94800,-509.89900,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10424,870966,28,15074,304444.090,76153.484,125475.130,14170,12839,15,7.152720e+12,...,0.034122,0.390212,0.003211,0.299250,0.317329,0.082210,333.19500,172.07700,70.60560,no
10425,870967,28,15240,165232.340,66270.766,57933.605,7690,13299,13,7.388280e+12,...,0.034059,0.387234,0.007786,0.362322,0.453900,0.090051,-99.56510,104.02400,142.64100,no
10426,870968,28,15272,272347.840,305951.750,303981.470,12676,2143,3,7.231790e+12,...,0.032024,0.447326,0.001472,0.255544,0.001987,0.043893,-333.16800,-55.94300,261.41000,no
10427,870969,28,15289,111759.160,122749.100,339429.380,5201,10670,9,7.085930e+12,...,0.030725,0.341775,0.007282,0.322402,0.242687,0.121855,75.08240,19.83800,-7.41744,no
10428,870970,28,15438,276200.190,56579.359,53757.617,12855,13750,15,7.295310e+12,...,0.032900,0.402439,0.007969,0.408591,0.606316,0.039734,-440.71800,322.18000,-177.03000,no

In [4]:
cl = df.copy()
cl['M500_msolh'] = np.log10(cl['M500_msolh'])
cl['T_kev'] = np.log10(cl['T_kev'])
cl['Lx_ergs'] = np.log10(cl['Lx_ergs'])
cl['Y500c'] = np.log10(cl['Y500c'])


cl

,# id,snap_id,uid,x,y,z,x_pixel,y_pixel,i_sector,M500_msolh,...,star_frac,T_kev,Lx_ergs,Y500c,M_sat_M_cD,cshift,vx,vy,vz,fossil
0,860542,28,0,208791.220,203940.950,349847.000,9718,6891,6,15.004824,...,0.028659,0.960115,1.578319,2.009912,0.027390,0.027437,-259.72600,-82.91320,-202.92100,yes
1,860543,28,1,314122.000,24372.678,278202.310,14620,15249,15,14.733386,...,0.030866,0.775219,0.898423,1.687803,0.111877,0.011779,-282.64600,1.06033,-293.46200,yes
2,860544,28,2,83855.367,206624.140,144593.690,3903,6766,4,14.860961,...,0.022724,0.788519,1.062717,1.771286,0.085323,0.063623,-40.43990,-160.57900,-72.43460,yes
3,860545,28,3,327261.750,233165.060,209430.580,15232,5531,7,14.798405,...,0.027928,0.791851,1.541992,1.738029,0.063246,0.037204,-9.51925,251.43900,-118.92500,yes
4,860546,28,4,183444.060,193161.880,332979.030,8538,7393,6,14.345895,...,0.026047,0.567016,0.321644,1.362738,0.216284,0.028688,870.24200,617.94800,-509.89900,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10424,870966,28,15074,304444.090,76153.484,125475.130,14170,12839,15,12.854471,...,0.034122,-0.408699,-2.493315,-0.523966,0.317329,0.082210,333.19500,172.07700,70.60560,no
10425,870967,28,15240,165232.340,66270.766,57933.605,7690,13299,13,12.868543,...,0.034059,-0.412027,-2.108688,-0.440906,0.453900,0.090051,-99.56510,104.02400,142.64100,no
10426,870968,28,15272,272347.840,305951.750,303981.470,12676,2143,3,12.859246,...,0.032024,-0.349376,-2.832007,-0.592534,0.001987,0.043893,-333.16800,-55.94300,261.41000,no
10427,870969,28,15289,111759.160,122749.100,339429.380,5201,10670,9,12.850397,...,0.030725,-0.466260,-2.137744,-0.491602,0.242687,0.121855,75.08240,19.83800,-7.41744,no
10428,870970,28,15438,276200.190,56579.359,53757.617,12855,13750,15,12.863044,...,0.032900,-0.395300,-2.098606,-0.388711,0.606316,0.039734,-440.71800,322.18000,-177.03000,no

In [ ]:
sns.lmplot(x = 'M500_msolh', y = 'Lx_ergs', hue="fossil", data=cl, fit_reg=True, ci = None, legend = True)
plt.xlabel('M, M_sun, log',fontsize=12)
plt.ylabel('L, 10^44 erg/s, log ', fontsize=12)
plt.title ('Dependency L/M')
plt.savefig('L-M.png')

print (len(cl[(cl.fossil == 'no')]))
print (len(cl[(cl.fossil == 'yes')]))

In [ ]:
##отсеим
cl.drop(cl[cl.M500_msolh < 13.5].index, inplace=True)
#cl.drop(cl[cl.M500_msolh > 34].index, inplace=True)
#df.drop(df[df.Lx_ergs > 20].index, inplace=True)
cl = cl.reset_index(drop=True)
cl

In [ ]:
sns.lmplot(x = 'M500_msolh', y = 'Lx_ergs', hue="fossil", data=cl, fit_reg=True, ci = None, legend = True)
plt.xlabel('M, M_sun, log',fontsize=12)
plt.ylabel('L, 10^44 erg/s, log ', fontsize=12)
plt.title ('Dependency L/M')
plt.savefig('L-M.png')

print (len(cl[(cl.fossil == 'no')]))
print (len(cl[(cl.fossil == 'yes')]))

In [ ]:
cl['fossil'] = 'no'
cl.loc[(cl.M_sat_M_cD<=0.1)&(cl.Lx_ergs>=(-1)),'fossil']='yes'
cl

In [ ]:
sns.lmplot(x = 'M500_msolh', y = 'Lx_ergs', hue="fossil", data=cl, fit_reg=True, ci = None, legend = True)
plt.xlabel('M, M_sun, log',fontsize=12)
plt.ylabel('L, 10^44 erg/s, log ', fontsize=12)
plt.title ('Dependency L/M')
plt.savefig('L-M.png')

print (len(cl[(cl.fossil == 'no')]))
print (len(cl[(cl.fossil == 'yes')]))

sns.lmplot(x = 'M500_msolh', y = 'T_kev', hue="fossil", data=cl, fit_reg=True, ci = None, legend = True)
plt.xlabel('M, M_sun, log',fontsize=12)
plt.ylabel('T, keV, log ', fontsize=12)
plt.title ('Dependency T/M')
plt.savefig('T-M.png')

sns.lmplot(x = 'T_kev', y = 'Lx_ergs', hue="fossil", data=cl, fit_reg=True, ci = None, legend = True)
plt.xlabel('T, keV, log',fontsize=12)
plt.ylabel('L, 10^44 erg/s, log', fontsize=12)
plt.title ('Dependency L/T')
#plt.savefig('T-L.png')

sns.lmplot(x = 'Lx_ergs', y = 'T_kev', hue="fossil", data=cl, fit_reg=True, ci = None, legend = True)
plt.xlabel('L, 10^44 erg/s, log ',fontsize=12)
plt.ylabel('T, keV, log', fontsize=12)
plt.title ('Dependency T/L')
plt.savefig('T-L.png')

sns.lmplot(x = 'M500_msolh', y = 'Y500c', hue="fossil", data=cl, fit_reg=True, ci = None, legend = True)
plt.xlabel('M, M_sun, log',fontsize=12)
plt.ylabel('Y500c, log', fontsize=12)
plt.title ('Dependency Y/M')
plt.savefig('Y-M.png')

In [ ]:
sns.lmplot(x = 'T_kev', y = 'Lx_ergs', hue="fossil", data=cl, fit_reg=True, ci = None, legend = True)
plt.xlabel('T, keV, log',fontsize=12)
plt.ylabel('L, 10^44 erg/s, log', fontsize=12)
plt.title ('Dependency L/T')

In [ ]:
df.star_frac[(df.fossil=='no')].hist(bins = 50, density = True)
df.star_frac[(df.fossil=='yes')].hist(bins = 50, alpha = 0.3, color = 'red', density = True)
plt.xlabel(r'star fraction, %')
plt.ylabel(r'Number of entries')
#plt.legend(loc='best')
plt.show()

df.gas_frac[(df.fossil=='no')].hist(bins = 50, density = True)
df.gas_frac[(df.fossil=='yes')].hist(bins = 50, alpha = 0.4, color = 'red', density = True)
plt.xlabel(r'gas fraction, %')
plt.ylabel(r'Number of entries')
#plt.legend(loc='best')
plt.show()

df.cshift[(df.fossil=='no')].hist(bins = 50, density = True)
df.cshift[(df.fossil=='yes')].hist(bins = 50, alpha = 0.45, color = 'red', density = True)
plt.xlabel(r'cshift')
plt.ylabel(r'Number of entries')
#plt.legend(loc='best')
plt.show()

In [ ]:
import glob

path = 'new' # use your path
all_files = glob.glob(path + "/*.csv")

li = []

for filename in all_files:
    
    df = pd.read_csv(filename, usecols = ['M_sat_M_cD'], header=0)
    df['name'] = filename
    li.append(df)
    #print(df)
    

frame = pd.concat(li, axis=0, ignore_index=True)
frame['fos'] = 1/frame.M_sat_M_cD

frame

In [ ]:
import plotly.express as px
import plotly

import plotly.io as pio
pio.renderers.default='notebook'

for filename in all_files:

    fig = px.histogram(frame.fos[(frame.name==filename)], nbins= len(frame.fos[(frame.name==filename)]), title = filename)
    fig.update_layout(autosize=False, width=1000, height=500, xaxis_range=[0,40])
    fig.show()
    print('median fossilness value = ', frame.fos[(frame.name==filename)].median(), 'Median galaxy ratio =', frame.M_sat_M_cD[(frame.name==filename)].median())